### ISSUE TITLE
 practica-de-diagrama-de-clases-equipo-bjy

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/practica-de-diagrama-de-clases-equipo-bjy#1]
[Diagrama de Clases - U4.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-equipo-bjy/files/7825387/Diagrama.de.Clases.-.U4.pdf)

**Comment by KarlaV0** [comment]
30%

**Comment by josealfredo79** [comment]
Al diagrama de clases en los métodos hace falta los pases de parametros

**Comment by josealfredo79** [comment]
Revisado
